# -*- coding: utf-8 -*-
"""01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

x = str(input())

a = x[0]
y = []
y.append(a)
for i in range (1,len(x)):
  if ( x[i] == a):
    y.append('$')
  else:
    y.append(x[i])
y1 = ''.join(map(str, y))
print(y1)