# -*- coding: utf-8 -*-
"""02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

x = []
n = int(input('len of the list'))

for i in range(n):
    y = int(input())

    x.append(y)

z = list(set(x))

print(z)