# -*- coding: utf-8 -*-
"""03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

x = []
n = int(input('len of the list'))

for i in range(n):
    y = int(input())

    x.append(y)

count_e = 0
count_o = 0

for i in x:
  if( i%2 == 0):
    count_e = count_e+1
  else:
    count_o = count_o+1


print(f"even count:  {count_e}")
print(f"odd count:  {count_o}")

for i in x:
  if( i%2 == 0):
    x.remove(i)
print(x)