# -*- coding: utf-8 -*-
"""04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

x = 4
for i in range(0,x):
    for j in range(0,i+1):
        print('*',end=' ')
    print()

for i in range(x,0,-1):
    for j in range(0,i-1):
        print('*',end=' ')
    print()