# -*- coding: utf-8 -*-
"""05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

for i in range(25,50+1):
 if (i>1):
  for j in range(2,i):
       if (i%j) == 0:
           break
  else:
        print(i)