# -*- coding: utf-8 -*-
"""07.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hZBd8Xjmxst3JPBU5rBF4VUcXyhl8NIw
"""

import matplotlib.pyplot as plt
import numpy as np

#### 7(i)#####

list1 = ['Toothpaste', 'Facewash', 'Shampoo', 'Moisturizer', 'Soap']
xpoints = np.array([1, 2, 3, 4, 5, 6])
ypoints_tp = np.array([2500, 2630, 2140, 3400, 3600, 2760])
ypoints_fw = np.array([1500, 1200, 1340, 1130, 1740, 1555])
ypoints_sm = np.array([5200, 5100, 4550, 5870, 4560, 4890])
ypoints_mt = np.array([9200, 6100, 9550, 8870, 7760, 7490])
ypoints_sp = np.array([1200, 2100, 3550, 1870, 1560, 1895])

plt.plot(xpoints, ypoints_tp)
plt.plot(xpoints, ypoints_fw)
plt.plot(xpoints, ypoints_sm)
plt.plot(xpoints, ypoints_mt)
plt.plot(xpoints, ypoints_sp)

plt.ylim(0,14000)  
plt.ylabel('Sales Unit')
plt.xlabel('Month No.')
plt.legend(list1,loc='upper right')
plt.show()



####### 7(ii) #######


plt.scatter(xpoints, ypoints_mt, label= "Moisturizer Sales", color= "green")
plt.legend()
plt.show()


####### 7(iii) #######

for i in range(0,6):
  x = xpoints[i]
  y = ypoints_tp[i]+ypoints_fw[i]+ypoints_sm[i]+ypoints_mt[i]+ypoints_sp[i]
  plt.bar(x,y)

plt.ylim(0,25000)
plt.ylabel('Total sale')
plt.xlabel('Month No.')
plt.show()